fixed bug when all free IDs are used and need to use a new.
Fixed a bug when the environment doesn't has a free ID unused and need to
use a new ID (last one +1)

Traceback (most recent call last):
  File "./poweradm.py", line 45, in <module>
    main_poweradm()
  File "/home/poweradm/PowerAdm/poweradm/poweradm.py", line 61, in main_poweradm
    createlparconf.exec_createlparconf()
  File "/home/poweradm/PowerAdm/poweradm/createlparconf.py", line 405, in exec_createlparconf
    lparconfig()
  File "/home/poweradm/PowerAdm/poweradm/createlparconf.py", line 151, in lparconfig
    lparid = freeid.mkID()
  File "/home/poweradm/PowerAdm/poweradm/newid.py", line 59, in mkID
    ids.sort(key=int)
ValueError: invalid literal for int() with base 10: 'None\n'